.github/workflows/test.yml, ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
Publish gyro info as well as accelerometer info.
```
$ rostopic echo /imu
```
Before
```
header: 
seq: 72
stamp: 
secs: 1704953902
nsecs: 635263919
frame_id: "/bodyset94472077639384"
orientation: 
x: 0.989590585231781
y: 0.13808977603912354
z: 0.020743228495121002
w: 0.03468123450875282
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
x: 0.0
y: 0.0
z: 0.0
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
x: 0.0
y: 0.0
z: 0.0
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
After
```
header:                   
seq: 1080                                                          
stamp:         
secs: 1704977204    
nsecs: 487167119     
frame_id: "/bodyset94472077639384" …
```
=> Publish gyro info

ros/kxr_controller/CMakeLists.txt
When installing the kxr_controller, a virtual environment is created using catkin virtualenv to avoid dependencies on the system environment. Since rcb4 is installed as a user installation, both users and developers can debug by editing the directories under rcb4/rcb4.
=> -e install rcb4 in virtualenv

rcb4/armh7interface.py, rcb4/units.py, ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
Related to https://github.com/iory/rcb4/pull/14
This PR sets the scales for gyro and acc to meters and degrees per second.
```
#!/usr/bin/env python
import rospy
from sensor_msgs.msg import Imu
import numpy as np
def callback(msg):
angular_norm = np.sqrt(msg.angular_velocity.x ** 2
+ msg.angular_velocity.y ** 2
+ msg.angular_velocity.z ** 2)
acc_norm = np.sqrt(msg.linear_acceleration.x ** 2
+ msg.linear_acceleration.y ** 2
+ msg.linear_acceleration.z ** 2)
if acc_norm > 1.4:
rospy.loginfo("Detect impact {}".format(acc_norm))
def listener():
rospy.init_node('listener', anonymous=True)
rospy.Subscriber("imu", Imu, callback, queue_size=10)
rospy.spin()
if __name__ == '__main__':
listener()
```
```
[INFO] [1705382302.899259]: Detect impact 1.4350709673397826
[INFO] [1705382304.198912]: Detect …
```
=> Adjust scale for acc and gyro

ros/kxr_controller/CMakeLists.txt, ros/kxr_controller/requirements.in, ros/kxr_controller/scripts/interface.py
```
~/ros/kxr  rosrun kxr_controller interface.py --viewer trimesh
Python 3.8.10 (default, Nov 22 2023, 10:22:35)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.3 -- An enhanced Interactive Python. Type '?' for help.
In [1]: ri.servo_on()
In [2]: ri.angle_vector(robot_model.init_pose(), 1)
Out[2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)
In [3]: robot_model.rarm_joint2_w.joint_angle(0.9)
Out[3]: 0.9
In [4]: ri.angle_vector(robot_model.angle_vector(), 0.1)
Out[4]: array([0. , 0.9, 0. , 0. , 0. , 0. , 0. , 0. , 0. ], dtype=float32)
In [5]: ri.angle_vector(robot_model.init_pose(), 1)
Out[5]: array([0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)
In [6]: ri.wait_interpolation()
Out[6]: True
```
=> Add interface.py

rcb4/struct_header.py
The type of rom_flash and rom_memory has been changed from uint8_t* to uint32_t.
This is because pointers are 32 bits length in the STM32 chip in the kondoh7 board.
=> Change variable type in SystemStruct

ros/kxr_controller/launch/kxr_controller.launch, ros/kxr_controller/scripts/interface.py, ros/kxr_models/node_scripts/http_server_node.py, ros/kxr_models/python/kxr_models/download_urdf.py, ros/kxr_models/python/kxr_models/ip.py, ros/kxreus/euslisp/kxr-interface.l
When considering a multimaster setup, each robot has its own roscore, and they each have a server IP and server port. This change involves adding a server_ip ROS parameter, allowing client-side PCs to reference various robots' rosmasters.
=> Add server_ip rosparam for multimaster

README.md, rcb4/apps/armh7_tool.py, rcb4/armh7interface.py, requirements.txt, setup.py
`armh7-tools` provides a comprehensive solution for calibrating and managing worm gear modules connected via the `ARMH7Interface`.
It facilitates the calibration of worm gears, reading of calibrated sensor data, and real-time display of sensor and worm gear values.
Designed for flexibility, it supports operations like calibration data update and in-place modification of YAML configuration files.
The calibration tool requires an input YAML file for worm gear modules configuration. 
This file contains a list of worm gears with their associated parameters: `worm_id`, `servo_id`, `sensor_id`,
and initial magnetic encoder value `magenc_init`.
Each worm gear is represented by a line in the YAML file with its parameters encapsulated in curly braces and prefixed by a dash, indicating a list item …
=> Enable armh tools

rcb4/armh7interface.py, rcb4/usb_utils.py, requirements.txt, ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
- Implement `reset_usb_device` function in `usb_utils.py` to reset USB device based on port.
- Modify `ARMH7Interface` class to reset USB device before initializing serial connection.
- Add `libusb1` dependency in `requirements.txt`.
=> Add USB reset functionality before opening serial port

rcb4/armh7interface.py, ros/kxr_controller/CMakeLists.txt, ros/kxr_controller/action/Stretch.action, ros/kxr_controller/msg/Stretch.msg, ros/kxr_controller/node_scripts/rcb4_ros_bridge.py, ros/kxr_controller/python/kxr_controller/kxr_interface.py, ros/kxreus/euslisp/kxr-interface.l
Python client
```
python3 interface.py 
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: ri.read_stretch()
Out[1]: 
joint_names: 
- joint1
- joint2
- joint3
- joint4
- joint5
- joint6
- joint7
- gripper_joint1
stretch: [10, 10, 10, 10, 10, 10, 10, 10]
In [2]: ri.send_stretch(30)
In [3]: ri.read_stretch()
Out[3]: 
joint_names: 
- joint1
- joint2
- joint3
- joint4
- joint5
- joint6
- joint7
- gripper_joint1
stretch: [30, 30, 30, 30, 30, 30, 30, 30]
```
Euslisp client
```
roseus kxr-interface.l
1.irteusgl$ kxr-init
13.irteusgl$ (let ((a (send *ri* :read-stretch))) (print (send a :joint_names)) (print (send a :stretch)))
("joint1" "joint2" "joint3" "joint4" …
```
=> Add stretch server and client to change servo stretch value from ROS system

ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
This PR catches the following exception.
```
Jun 25 17:04:20 humid-illusion user.service[3529]: '[ERROR] [1719302615.575514] [/rcb4_ros_bridge:rosout]: Exception in your execute callback: Timeout: No data received.
Jun 25 17:04:20 humid-illusion user.service[3529]: Traceback (most recent call last):
Jun 25 17:04:20 humid-illusion user.service[3529]:   File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
Jun 25 17:04:20 humid-illusion user.service[3529]:     self.execute_callback(goal)
Jun 25 17:04:20 humid-illusion user.service[3529]:   File "/home/rock/ros/kxr/src/rcb4/ros/kxr_controller/node_scripts/rcb4_ros_bridge.py", line 379, in servo_on_off_callback
Jun 25 17:04:20 humid-illusion user.service[3529]: …
```
=> Add SerialException in servo_on_off_callback()

rcb4/armh7interface.py
`velocity`, argument of servo_angle_vector and other functions, can be misleading 
since it actually represents duration.
kondoh7 reads velocity [here](https://github.com/jsk-ros-pkg/control_boards/blob/3440bec59c9229900d410a767edd405da3c8d194/projects/kondoh7/Core/Src/rcb4emulate.c#L573) in the following way :
`Control.move_time = inst[7] * FRAME_SCALE;`
Default value of FRAME_SCALE is 10, defined at [main.h](https://github.com/jsk-ros-pkg/control_boards/blob/3440bec59c9229900d410a767edd405da3c8d194/projects/kondoh7/Core/Inc/main.h#L86C24-L86C64).
=> Fix velocity description of servo_angle_vector()

ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
This change allows users to use kxr_controller even if URDF is not given.
Dummy URDF is genarated using the information in servo config.
=> Make dummy urdf if urdf_path is not set

ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
This PR fixes the following error.
```
Aug 02 16:00:11 plucky-moonshadow user.service[4061]: Traceback (most recent call last):                                                                                                                                                                              
Aug 02 16:00:11 plucky-moonshadow user.service[4061]:   File "/home/rock/ros/kxr/devel/lib/kxr_controller/rcb4_ros_bridge.py", line 15, in <module>                                                                                                                   
Aug 02 16:00:11 plucky-moonshadow user.service[4061]:     exec(compile(fh.read(), python_script, 'exec'), context) …
```
=> Initialize self.interface every time

ros/kxr_controller/CMakeLists.txt, ros/kxr_controller/msg/ServoOnOff.msg, ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
Publish `~state` topic so that nodes other than `rcb4_ros_bridge` (e.g. `button_action_manager.py`) can get the ON/OFF status of the servo.
=> Publish servo on/off state

ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
Sometimes `rcb4_ros_bridge.py` fails with the following error.
```
Aug 16 15:07:44 amplifying-lichen user.service[3029]: '[ERROR] [1723788457.335167] [/rcb4_ros_bridge:rosout]: [publish_pressure] Timeout: No data received.'
Aug 16 15:07:44 amplifying-lichen user.service[3029]: Exception in thread Thread-11:
Aug 16 15:07:44 amplifying-lichen user.service[3029]: Traceback (most recent call last):
Aug 16 15:07:44 amplifying-lichen user.service[3029]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Aug 16 15:07:44 amplifying-lichen user.service[3029]:     self.run()
Aug 16 15:07:44 amplifying-lichen user.service[3029]:   File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 237, in run
Aug 16 15:07:44 amplifying-lichen user.service[3029]: …
```
=> Add sleep(0.1) before publishing topic

rcb4/armh7interface.py, rcb4/data/__init__.py, rcb4/struct_header.py, ros/kxr_controller/CMakeLists.txt, ros/kxr_controller/action/PressureControl.action, ros/kxr_controller/launch/kxr_controller.launch, ros/kxr_controller/msg/PressureControl.msg, ros/kxr_controller/node_scripts/rcb4_ros_bridge.py, ros/kxr_controller/python/kxr_controller/kxr_interface.py, ros/kxreus/euslisp/kxr-interface.l
Set `control_pressure` as true.
```
<launch>
<include file="$(find kxr_controller)/launch/kxr_controller.launch">
<arg name="urdf_path" value="$(find yamaguchi_7axis_arm_no_worm_with_vacuum_base_ver3)/urdf/yamaguchi_7axis_arm_no_worm_with_vacuum_base_ver3_color.urdf" />
<arg name="servo_config_path" value="$(find yamaguchi_7axis_arm_no_worm_with_vacuum_base_ver3)/config/servo_config.yaml" />
<arg name="publish_sensor" value="false" />
<arg name="control_pressure" value="true" />
<arg name="control_loop_rate" value="20" />
</include>
</launch>
```
Set `threshold` field as -10 and `release` field as false.
Shell
```
$ rostopic pub /kxr_fullbody_controller/pressure_control_interface/goal kxr_controller/PressureControlActionGoal "header:
seq: 0
stamp:
secs: 0
nsecs: 0
frame_id: ''
goal_id: …
```
=> Add PressureControl ROS server and client

rcb4/data/__init__.py
Since pump power board rev.3 switches the pump and solenoid valve in GPIO open-drain mode, the kondoh7 firmware was changed to v0.6.5.
The original firmware is found in https://github.com/nakane11/control_boards/tree/air-relay-rev2.
Before merging, please put the following files in https://github.com/iory/rcb4/releases/download/v0.6.5.elf/v0.6.5.elf.
v0.6.5.elf: https://github.com/nakane11/control_boards/releases/download/v0.6.5/v0.6.5.elf
=> Add v0.6.5 elf file

ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
This PR catch the following error, which may occur when plugging and unplugging kondoh7.
```
Oct 21 22:44:56 plucky-moonshadow user.service[2944]: Traceback (most recent call last):    
Oct 21 22:44:56 plucky-moonshadow user.service[2944]:   File "/home/rock/ros/kxr/devel/lib/kxr_controller/rcb4_ros_bridge.py", line 15, in <module>
Oct 21 22:44:56 plucky-moonshadow user.service[2944]:     exec(compile(fh.read(), python_script, 'exec'), context)
Oct 21 22:44:56 plucky-moonshadow user.service[2944]:   File "/home/rock/ros/kxr/src/rcb4/ros/kxr_controller/node_scripts/rcb4_ros_bridge.py", line 776, in <module>
Oct 21 22:44:56 plucky-moonshadow user.service[2944]:     ros_bridge.run()                     
Oct 21 22:44:56 plucky-moonshadow user.service[2944]:   File …
```
=> Add new try-catch in publish_joint_states()

ros/kxr_controller/msg/ServoOnOff.msg, ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
In this pull request, joint names are now published within the ServoOnOff message.
Additionally, instead of assigning values to self.joint_servo_on within servo_on_off_callback(), this has been standardized to use self.check_servo_states().
=> Publish joint names in ServoOnOff msg

ros/kxr_controller/launch/kxr_controller.launch, ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
With this change, an empty urdf_path can be put in the arg of the launch file.
=> Allow empty urdf_path

rcb4/apps/write_firmware.py
If command line argument is given, use the argument as elf file path.
```
$ rcb4-write-firmware ~/Downloads/air_relay_rev2.elf 
Checking dependencies...
Dependencies are satisfied.
Locating ST-Link path...
ST-Link path found: /home/naoya/.rcb4/stlink/stlink-1.7.0/build/Release/bin/st-flash
Retrieving latest ELF file...
ELF file found: /home/naoya/Downloads/air_relay_rev2.elf
Converting ELF to BIN: /home/naoya/Downloads/air_relay_rev2.bin
ELF successfully converted to BIN.
Flashing BIN to device...
BIN successfully flashed to device.
```
I need this feature for air relay firmware.
=> Any elf file is available by write_firmware.py

ros/kxr_controller/node_scripts/rcb4_ros_bridge.py, ros/kxr_controller/python/kxr_controller/multi_lock.py
- Control multiple air works using multiple threads via pressure control actionlib
- For example, A single pump is used for
- adsorption of the robot base to the wall surface and
- for object grasping by the robot arm.
- Assume Air_Work_A and Air_Work_B start at about the same time and Air_Work_A finishes before Air_Work_B.
- The Air_Work_A controller turns off the pump as soon as Air_Work_A is finished, but this prevents Air_Work_B from being completed.
- Add MultiLock class to restrict access to commonly used pump and solenoid valve
- Control multiple air works using MultiLock
- If you control only one air work, there is no change.
- I've used many different ways of two air works. However there is possibly a case that causes a deadlock.
=> Control multiple air works using multiple threads

ros/kxr_controller/action/PressureControl.action, ros/kxr_controller/msg/PressureControl.msg, ros/kxr_controller/node_scripts/rcb4_ros_bridge.py, ros/kxr_controller/python/kxr_controller/kxr_interface.py
- Change `PressureControl` message field for easy understanding.
- start_pressure -> trigger_pressure
- stop_pressure -> target_pressure
- Add release_duration field. The duration to open air_connect_valve.
This PR depends on https://github.com/iory/rcb4/pull/141, https://github.com/iory/riberry/pull/107
=> Update PressureControl msg: change field name and add release_duration

ros/kxr_controller/python/kxr_controller/kxr_interface.py
When creating an instance of KXRROSRobotInterface without explicitly providing a namespace, the parent class constructor overwrites [self.namespace with None](https://github.com/iory/scikit-robot/blob/46b0066c3ef141873058846aad8134de51447e3e/skrobot/interfaces/ros/base.py#L107). This causes the following error:
```
Traceback (most recent call last):
File "/home/rock/ros/kxr/src/hand_v3/node_scripts/hand_interface.py", line 60, in __init__
self.ri = KXRROSRobotInterface(  # NOQA
File "/home/rock/ros/kxr/src/rcb4/ros/kxr_controller/python/kxr_controller/kxr_interface.py", line 35, in __init__
super(KXRROSRobotInterface, self).__init__(*args, **kwargs)
File "/home/rock/ros/kxr/src/scikit-robot/skrobot/interfaces/ros/base.py", line 123, in __init__
self.controller_actions = …
```
=> Avoid TypeError in default_controller()

.clang-format, .github/workflows/test.yml, README.md, ros/kxr_controller/include/kxr_controller/kxr_robot_hardware.h, ros/kxr_controller/src/kxr_robot_hardware.cpp
To install `clang-format`, you can use the following command:
```
sudo apt-get install clang-format
```
Once installed, you can format your files using a `.clang-format` configuration file. To format a file, run:
```
clang-format -i <filename>
```
Replace `<filename>` with the name of the file you want to format. The `-i` option tells `clang-format` to edit the file in place.
=> Apply and add clang-format

.github/workflows/test.yml, pyproject.toml, rcb4/armh7interface.py, ros/kxr_controller/CMakeLists.txt, ros/kxr_controller/cfg/KXRParameters.cfg, ros/kxr_controller/node_scripts/rcb4_ros_bridge.py, ros/kxreus/requirements.in
Fixing typos in robot software development improves code readability, reduces bugs, enhances maintainability, prevents misinterpretations in logs and documentation, and ensures smooth CI/CD processes. Typos can lead to incorrect variable references, misunderstandings, and potential safety risks in robotic operations. 
- Added a new typos job in .github/workflows/test.yml to automatically check for typos using typos-action.
Typo tests are not perfect, but they improve code maintainability and prevent developers from being distracted by minor mistakes.
=> [Github Actions] Add test to fix typos

ros/kxr_controller/node_scripts/rcb4_ros_bridge.py
Fixed a typo by renaming KXRParameteresConfig to KXRParametersConfig (https://github.com/iory/rcb4/pull/168). 
Made this change to ensure that the script still works even if other users pull the latest changes without rebuilding.
=> Handle missing KXRParametersConfig import with fallback message for backward compatibility

ros/kxr_controller/node_scripts/rcb4_ros_bridge.py, ros/kxr_controller/python/kxr_controller/multi_lock.py
If PressureControl action is resent while the pump is running with the same ID, it causes `air_work_on` to be  reinitialized to `False` even though it is actually `True`, and the pump cannot stop.
I fixed initialization with `air_work_on=True` when lock is applied, since lock is always released when `air_work_on` is `False`.
=> Fix air_work_on initialization to match actual state

ros/kxr_controller/CMakeLists.txt, ros/kxreus/CMakeLists.txt
This commit adds detection for the Radxa Zero platform by reading the /proc/device-tree/model file. If the device is identified as a Radxa Zero, the default value for USE_VIRTUALENV is set to OFF to avoid compatibility issues on this architecture. For other platforms, the default remains ON.
=> Set default USE_VIRTUALENV=OFF on Radxa Zero boards

requirements.txt
Using numpy versions earlier than 1.22.0 can cause the following errors, which may be difficult for beginners to debug:
```
ModuleNotFoundError: No module named 'numpy.typing'
AttributeError: module 'numpy' has no attribute 'typeDict'
```
=> Update numpy version

ros/kxr_controller/launch/kxr_controller.launch, ros/kxr_controller/node_scripts/rcb4_ros_bridge.py, ros/kxr_controller/src/kxr_robot_hardware.cpp
This PR increases loop rate by not using `rospy.get_param()` each time in the run() loop.
- If `control_loop_rate` is 30, /current_joint_states rate is about 30.
- If `control_loop_rate` is 100, /current_joint_states rate is about 40.
Launch
```
<include file="$(find kxr_controller)/launch/kxr_controller.launch">
<arg name="urdf_path" value="$(find yamaguchi_7axis_arm_no_worm_with_vacuum_base_ver10)/urdf/yamaguchi_7axis_arm_no_worm_with_vacuum_base_ver10.urdf" />
<arg name="servo_config_path" value="$(find yamaguchi_7axis_arm_no_worm_with_vacuum_base_ver10)/config/servo_config.yaml" />
<arg name="publish_sensor" value="false" />
<arg name="publish_imu" value="false" />
<arg name="publish_battery_voltage" value="false" />
<arg name="control_pressure" value="true" />
<arg …
```
=> Set default control loop rate to 30

ros/kxr_controller/launch/kxr_controller.launch, ros/kxr_controller/package.xml, ros/kxr_controller/python/kxr_controller/kxr_interface.py, ros/kxr_controller/python/kxr_controller/reconfigure_utils.py, ros/kxr_controller/src/kxr_robot_hardware.cpp
Added a mux to support leader-follower control by relaying one robot's joint states directly as command inputs to the other, allowing separation from ROS Control outputs.
=> Add update_kxr_parameters to change dynamic reconfigure params and command joint state mux
